title:  Data Lesson Catalog
description: A test development site that will host a catalog of data lessons submitted by the community.

#use this when pushing to git for live version
url:       http://data-training.github.io/data-lesson-catalog
baseurl:	http://data-training.github.io/data-lesson-catalog

# use this when working locally
#url: http://localhost:4000

disqus_shortname: datalessoncatalog

# Social networking links are used in author-bio sidebar. Update and remove as you like.

# Owner/author information
owner:
  name: Data Lesson Catalog
  avatar: profilePic_circle.png
  bio: "A central repository for education content related to working with data."
  email: "datalessons@gmail.com"
  twitter: ""
  github: "data-training"
  youtube:
# instagram:      ""
# For Google Authorship https://plus.google.com/authorship
# google_plus:    ""

# Analytics and webmaster tools stuff goes here
google_analytics:

# Links to include in top navigation
# For external links add external: true

links:
  - title: Data Tutorials
    url: /activities/

  - title: About
    url: /about/

  - title: Courses
    url: /course/

  - title: Data Lessons
    url: /data-lessons/

  - title: Submit A Lesson, Course or Workshop
    url: /submit/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Denver
future:      true
# turning off pygments for the time being
#pygments:    true
#highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
